apiVersion: v1
kind: Service
metadata:
  name: cloud-native-python-mongodb-service
  labels:
    app: cloud-native-python-mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: cloud-native-python-mongodb